### PR TITLE
Improve system stability

### PR DESCRIPTION
**Pull request by 173210**

### CODE REVIEW

**Comment by kot2002** [comment]
I tried this with 173210/libkhax@40b0464cb45832ebdd424e48638668c91455d167 on O3DS 9.0E.
Launching rxTools with HBL (themehax, 2.5) 8/10
(2 were black freeze. no themehax-related failure was counted.)
Using BootCTR (built with those commits) to launch rxTools 15/15

**Comment by 173210** [comment]
@kot2002 You used CakeBrah, right? CakeBrah also needs a patch (mid-kid/CakeBrah#5)

**Comment by kot2002** [comment]
Of course, I merged that patch.

**Comment by 173210** [comment]
Hmm, it should be difficult to investigate the bug because it rarely occurs (I don't have much time to try 10 times for each build).
Anyway, the patch is ready to merge, because it actually improves the boot rate (CakeBrah without this patch rarely worked on my new 3DS).

**Comment by kot2002** [comment]
I agree with you. This gives decent boot rate for now.

**Comment by 173210** [comment]
Added commit 3ca81fa5edbd4afbf80991a28296e5729832ba0d.

**Comment by mid-kid** [comment]
Many thanks for your contribution.

**Pull request merged**
