### PR TITLE
Use libkhax for compatibility and stability.

### PR DESCRIPTION
**Pull request by ghost**
This PR replaces Brahma's ARM11 hax with libkhax. The aim is to no longer require the HB service, adding support for Ninjhax 2.x/etc, while still providing 100% stability, unlike other solutions that introduce instability.

This will work on O3DS Ninjhax 2, however it does not yet work on N3DS Ninjhax 2, much like the other solution. libkhax will need to be fixed for N3DS Ninjhax 2.

### CODE REVIEW

**Comment by mid-kid** [comment]
Ooh, lookin' nice.
Could you try using libkhax as a git submodule instead of copying it's files?
NOTE: I'll be gone for the week, may not be able to respond further.

**Comment by ghost** [comment]
I did originally try that, but libkhax's test main.c was conflicting with CakeBrah's main.c. Not the main function, as that can be disabled with a flag, but the compiled object names.

**Comment by mid-kid** [comment]
You could try using GNU make's filter-out function to filter source/libkhax/main.c from the CFILES array. (Or leave me do it at some later point)
Reference: https://www.gnu.org/software/make/manual/make.html#Text-Functions

**Comment by ghost** [comment]
I'm probably doing something wrong, but I'm getting this after trying to do that:

```
linking Cakes.elf
main.o: In function `main':
CakeBrah/source/main.c:10: multiple definition of `main'
main.o:CakeBrah/source/main.c:10: first defined here
```

**Comment by mid-kid** [comment]
`CFILES      :=  $(foreach dir,$(SOURCES),$(notdir $(filter-out source/libkhax/main.c, $(wildcard $(dir)/*.c))))`
notdir removes the path, making the filter-out useless.

**Comment by ghost** [comment]
EDIT: Disregard, it works.

**Comment by mid-kid** [comment]
Did you clean? Because it works for me.

**Comment by ghost** [comment]
Yeah, I just realized I messed up on something; it works now. I'll update the PR.

**Comment by mid-kid** [comment]
Neato. Don't mind me holding back this pull request until n3ds support is sorted out, though.

**Comment by ghost** [comment]
Sounds fair to me. Been working on figuring it out to the best of my ability with my O3DS.

**Comment by ghost** [comment]
Removed the Makefile change; I just got a PR in to libkhax to move the demo files into a separate directory.

**Comment by ghost** [comment]
Should work on N3DS now.

**Pull request merged**
