### PR TITLE
Fix firmware 7.2 offsets

### PR DESCRIPTION
**Pull request by A600**

### CODE REVIEW

**Comment by mid-kid** [comment]
Maybe it's a good idea to commit this to upstream Brahma too?

**Comment by b1l1s** [comment]
Agreed. Would have to redo the commit for their repo though I think (I don't git so good).

**Comment by mid-kid** [comment]
Check out the git cherry-pick command (and documentation). As long as there are no conflicts (I don't see why there'd be any), it's automagical. Otherwise, just be lazy and let me do it.

**Comment by b1l1s** [comment]
> Otherwise, just be lazy and let me do it.

That sounds like a plan. :P

**Pull request merged**
